# Basic setting
MAP_SIZE = (200, 100)
BARRIER_PERCENTAGE = 0.1
BOT_NUMS = 5

# Robot exploring setting
BOT_COMMUNICATE_RANGE = 10
BOT_MOVING_RANGE = 5
PROFIT_RATIO = 0.5
PHE_RATIO = 0.5
PHE_VOLATILIZE_CAP = 0.05
