# Basic setting
MAP_SIZE = (100, 75)
BARRIER_PERCENTAGE = 0.03
BOT_NUMS = 10

# Robot exploring setting
BOT_COMMUNICATE_RANGE = 10
BOT_MOVING_RANGE = 5
BOT_SENSOR_RANGE = 5
PROFIT_RATIO = 0.5
PHE_RATIO = 0.5
PHE_VOLATILIZE_CAP = 0.05

# Gui setting
ZOOM_SIZE = 10
COLOR_MAP = {
    ''
}
